### ISSUE TITLE
Changing domain name resolver from google to cloudflare's one

### ISSUE THREAD

**Issue by palindrom615** [ToonRaon/ToonRaonConnector#12]
Hi!

This batch file sets dns server as google dns 8.8.8.8 server. It is reported that cloudflare dns server 1.1.1.1 shows improved resolving performance than google's.

1.1.1.1 server also support DNS over HTTPS! You can guess why it is killing feature:)

How about considering to change dns server?

지금 사용하고 있는 구글 8.8.8.8 dns 서버보다 1.1.1.1 클라우드플레어 서버가 더 나은 성능을 보여준다고 보고되고 있습니다.

또 1.1.1.1은 DoH 기능을 지원하구요. 사지방 이용자에게 중요한 기능이죠:)

dns 서버를 1.1.1.1로 바꾸는 것은 어떻습니까?

**Comment by ToonRaon** [comment]
한 번 바꿔봐야겠네요 의견 감사합니다
